#!/bin/bash

# Get current working directory scripts/ and define paths.
SCRIPTS_DIR=$(dirname "$(readlink -f "$0")")
DOCKER_DIR=$(readlink -f "$SCRIPTS_DIR/..")
BIN_DIR=$(readlink -f "$SCRIPTS_DIR/../../bin")

ENV_FILE="$DOCKER_DIR/.env"

echo "🔧 Starting MCCE4-Alpha Setup..."

# --- Development Mode ---
if [[ "$1" == "-d" ]]; then

    # --- Environment Sync (.env) ---
    echo "📝 Detecting host IDs for Docker permissions..."
    # NOTE: This avoids 'readonly' shell issues
    DETECTED_UID=$(id -u)
    DETECTED_GID=$(id -g)

    cat << EOF > "$ENV_FILE"

# Auto-generated by setup.sh
# This allows Docker Compose to sync container permissions with your host user.
USER_UID=$DETECTED_UID
USER_GID=$DETECTED_GID
EOF

    echo "✅ Created .env at $ENV_FILE (UID=$DETECTED_UID, GID=$DETECTED_GID)"

fi

# --- Interactive PATH Setup ---
BIN_PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\""

# 1. Detect which config file to use (Basic detection)
SHELL_CONFIG="$HOME/.bashrc"
if [[ "$SHELL" == *"zsh"* ]]; then
    SHELL_CONFIG="$HOME/.zshrc"
fi

echo "🔍 Checking $SHELL_CONFIG..."

# 2. Idempotency Check (Don't add if it's already there)
if grep -q "$BIN_DIR" "$SHELL_CONFIG"; then
    echo "✅ Your PATH is already configured correctly in $SHELL_CONFIG."
else
    # 3. Interactive Prompt
    echo "⚠️  The MCCE4 CLI is not in your PATH yet."
    echo "   Would you like this script to append it to $SHELL_CONFIG now? (y/n)"
    read -r -p "   > " response
    
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        echo "" >> "$SHELL_CONFIG" # Newline for safety
        echo "# MCCE4-Alpha CLI" >> "$SHELL_CONFIG"
        echo "$BIN_PATH_LINE" >> "$SHELL_CONFIG"
        echo "✅ Successfully added to $SHELL_CONFIG"
        echo "   👉 Please run: source $SHELL_CONFIG"
    else
        echo "🆗 Skipped. You can manually add the line below to your .bashrc file:"
        echo "   $BIN_PATH_LINE"
        echo "👉 Then run: source $SHELL_CONFIG"
    fi
fi