#!/bin/bash

# Get current working directory scripts/ and define paths.
SCRIPTS_DIR=$(dirname "$(readlink -f "$0")")
DOCKER_DIR=$(readlink -f "$SCRIPTS_DIR/..")
BIN_DIR=$(readlink -f "$SCRIPTS_DIR/../../bin")

ENV_FILE="$DOCKER_DIR/.env"

echo "🔧 Starting MCCE4-Alpha Developer Setup..."

# --- Environment Sync (.env) ---
echo "📝 Detecting host IDs for Docker permissions..."
# NOTE: This avoids 'readonly' shell issues
DETECTED_UID=$(id -u)
DETECTED_GID=$(id -g)

cat << EOF > "$ENV_FILE"

# Auto-generated by setup.sh
# This allows Docker Compose to sync container permissions with your host user.
USER_UID=$DETECTED_UID
USER_GID=$DETECTED_GID
EOF

echo "✅ Created .env at $ENV_FILE (UID=$DETECTED_UID, GID=$DETECTED_GID)"

# # --- CLI Permissions ---
# echo "🔐 Making CLI scripts executable..."
# chmod +x "$SCRIPTS_DIR"/*
# echo "✅ All scripts in $SCRIPTS_DIR are now executable."

# --- PATH Instructions ---
echo ""
echo "🚀 FINAL STEP: To use 'mc4' from anywhere, add this to your ~/.bashrc or ~/.zshrc:"
echo "----------------------------------------------------------------"
echo "export PATH=\"$BIN_DIR:\$PATH\""
echo "----------------------------------------------------------------"
echo "Then run: source ~/.bashrc (or restart your terminal)"