#!/bin/bash

# Get the directory where the script is (Docker/scripts)
# then go up one level to the Docker/ directory
DOCKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$DOCKER_DIR/.env"

echo "Detecting host IDs..."

# Get current IDs using the command directly to avoid 'readonly' shell issues
DETECTED_UID=$(id -u)
DETECTED_GID=$(id -g)

# Create or overwrite the .env file in the Docker/ directory
cat << EOF > "$ENV_FILE"
# Auto-generated by setup_env.sh
# This allows Docker Compose to sync container permissions with your host user.
USER_UID=$DETECTED_UID
USER_GID=$DETECTED_GID
EOF

echo "Success! Created .env at $ENV_FILE"
echo "Values: UID=$DETECTED_UID, GID=$DETECTED_GID"