FROM condaforge/miniforge3

LABEL com.mcce4.image.authors="Julian A. Rendon" \
    com.mcce4.image.description="MCCE4-Alpha Docker Environment" \
    com.mcce4.image.source="https://github.com/GunnerLab/MCCE4-Alpha" \
    com.mcce4.image.maintainer="Gunner Lab"

# Install system tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    build-essential \
    curl \
    git \
    iproute2 \
    net-tools \
    openssh-client \
    sudo \
    tree && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cd /tmp && \
    wget https://github.com/apptainer/apptainer/releases/download/v1.4.5/apptainer_1.4.5_amd64.deb && \
    apt-get update && apt-get install -y \
    ./apptainer_1.4.5_amd64.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Node via Conda
# RUN conda install -c conda-forge nodejs

# These are fallbacks. They will be OVERWRITTEN by your Docker Compose args.
ARG USERNAME=mc4
ARG USER_UID=1000
ARG USER_GID=1000

# Take over existing 'ubuntu' user: rename it, sync IDs, and update home path.
# Necessary when working with mounted volumes.
RUN groupmod -n $USERNAME ubuntu && \
    groupmod -g $USER_GID $USERNAME && \
    usermod -l $USERNAME -u $USER_UID -g $USER_GID -m -d /home/$USERNAME ubuntu

# Switch from root to the new user for security and file ownership parity.
USER $USERNAME
WORKDIR /home/mc4

ENV PATH="/home/mc4/.conda/envs/mc4/bin:/home/mc4/MCCE4-Alpha/bin:/home/mc4/MCCE4-Alpha/MCCE_bin:${PATH}"
ENV CONDA_DEFAULT_ENV="mc4"

# Optional: Ensure bash is used for RUN commands later (if you add any)
SHELL ["/bin/bash", "-l", "-c"]

# Keep the container running indefinitely so we can access it via exec
CMD ["tail", "-f", "/dev/null"]